//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTService.LevelUpServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LevelUpServiceRef.ILog")]
    public interface ILog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILog/AddEntry", ReplyAction="http://tempuri.org/ILog/AddEntryResponse")]
        DataAccess.LogEntry AddEntry(string typeOfExercise, string distance, string minutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILog/AddEntry", ReplyAction="http://tempuri.org/ILog/AddEntryResponse")]
        System.Threading.Tasks.Task<DataAccess.LogEntry> AddEntryAsync(string typeOfExercise, string distance, string minutes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogChannel : RESTService.LevelUpServiceRef.ILog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogClient : System.ServiceModel.ClientBase<RESTService.LevelUpServiceRef.ILog>, RESTService.LevelUpServiceRef.ILog {
        
        public LogClient() {
        }
        
        public LogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataAccess.LogEntry AddEntry(string typeOfExercise, string distance, string minutes) {
            return base.Channel.AddEntry(typeOfExercise, distance, minutes);
        }
        
        public System.Threading.Tasks.Task<DataAccess.LogEntry> AddEntryAsync(string typeOfExercise, string distance, string minutes) {
            return base.Channel.AddEntryAsync(typeOfExercise, distance, minutes);
        }
    }
}
