// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Changedheightandweighttodouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedheightandweighttodouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050907145_Changed height and weight to double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
